# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

# Change 'AirMapsExplorer' to match the target in your Xcode project.
target 'Onedoor' do
    rn_path = '../node_modules/react-native' # This path is likely to be `../node_modules/react-native` in your own project.
    rn_maps_path = '../node_modules/react-native-maps' # This path is likely to be `../node_modules/react-native-maps` in your own project.
    
    # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    ]
    
    # React Native third party dependencies podspecs
    pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
    pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
    pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
    
    # react-native-maps dependencies
    pod 'react-native-maps', path: rn_maps_path
    pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
    pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
    pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
#    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    
    # pod 'react-native-add-calendar-event', :path => '../node_modules/react-native-add-calendar-event'
    
    # pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
    
#  pod 'Picker', :path => '../node_modules/react-native-picker'

#    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

#    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    
#  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
#
#  pod 'react-native-video', :path => '../node_modules/react-native-video'
#
#  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

#  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        if target.name == "React"
            target.remove_from_project
        end
        
        if target.name == "yoga"
            target.remove_from_project
        end
    end
end
